# Default values for splunk-kubernetes-logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# = Global Configs =
# Allow to pass config values from parent chart using `global.*`.
# Global values have lower priority.
# Values defined here are the default values.
global:
  logLevel: debug
  splunk:
    hec:
      port: 8088
      protocol: https
      insecureSSL: false


# = Log Level =
# logLevel is to set log level of the Splunk kubernetes metrics collector. Avaiable values are:
# * debug
# * info
# * warn
# * error
#
# Default value: "info"
logLevel:


rbac:
  # Specifies whether RBAC resources should be created.
  # This should be set to `false` if either:
  # a) RBAC is not enabled in the cluster, or
  # b) you want to create RBAC resources by yourself.
  create: true


serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:


# = Splunk HEC Connection =
splunk:
  # Configurations for HEC (HTTP Event Collector)
  hec:
    # hostname/ip of HEC, REQUIRED.
    host:
    # port to HEC, OPTIONAL. Default value: 8088
    port:
    # the HEC token, REQUIRED.
    token:
    # protocol has two options: "http" and "https". Default value: "https"
    protocol:
    # indexName tells which index to use, OPTIONAL. If it's not present, the default index configured in HEC will be used.
    indexName:
    # insecureSSL is a boolean, it indecates should it allow inscure SSL connection (when protocol is "https"). Default value: false
    insecureSSL:
    # The PEM-format CA certificate for this client.
    # NOTE: The content of the certificate itself should be used here, not the file path.
    #       The certificate will be stored as a secret in kubernetes.
    clientCert:
    # The private key for this client.
    # NOTE: The content of the key itself should be used here, not the file path.
    #       The key will be stored as a secret in kubernetes.
    clientKey:
    # The PEM-format CA certificate file.
    # NOTE: The content of the file itself should be used here, not the file path.
    #       The file will be stored as a secret in kubernetes.
    caFile:


image:
  name: dummy-user/dummy-repo:dummy-tag
  pullPolicy: Always


imageAgg:
  name: dummy-user/dummy-repo:dummy-tag
  pullPolicy: Always


resources:
  fluent:
    # limits:
    #   cpu: 200m
    #   memory: 300Mi
    requests:
      cpu: 200m
      memory: 300Mi


# Controls the output buffer for fluentd.
 # Note that, for memory buffer, if `resources.sidecar.limits.memory` is set,
 # the total buffer size should not bigger than the memory limit, it should also
 # consider the basic memory usage by fluentd itself.
 # All buffer parameters (except Argument) defined in
 # https://docs.fluentd.org/v1.0/articles/buffer-section#parameters
 # can be configured here.
buffer:
  "@type": memory
  total_limit_size: 400m
  chunk_limit_size: 100m
  chunk_limit_records: 1000000
  flush_interval: 5s
  flush_thread_count: 1
  overflow_action: block
  retry_max_times: 3


aggregatorBuffer:
  "@type": memory
  total_limit_size: 400m
  chunk_limit_size: 100m
  chunk_limit_records: 1000000
  flush_interval: 5s
  flush_thread_count: 1
  overflow_action: block
  retry_max_times: 3


nodeSelector: {}
  # kubernetes.io/role: master


# This default tolerations allow the daemonset to be deployed on master nodes,
# so that we can also collect metrics from those nodes.
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule


affinity: {}
